# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180508_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Message',
        ),
    ]
